export const GODS = [
  {
    id: 'mylin',
    name: 'Mylin',
    domains: ['Mercy', 'Shelter'],
    generation: 'First',
    rarity: 'common',
    districtAffinity: 'heart',
    shrineText: 'A quiet alcove of warm stone, hung with simple offerings.',
    blessing: { type: 'MORNING_CAMP', value: -8, duration: 'CYCLE' },
  },
  {
    id: 'paiz',
    name: 'Paiz',
    domains: ['Insight', 'Schemes'],
    generation: 'Second',
    rarity: 'uncommon',
    districtAffinity: 'arcane',
    shrineText: 'A lattice of runes pulses with soft, patient light.',
    blessing: { type: 'PACK_POWER', value: 1, duration: 'NIGHT' },
  },
  {
    id: 'vilyn',
    name: 'Vilyn',
    domains: ['Growth', 'Thickets'],
    generation: 'First',
    rarity: 'common',
    districtAffinity: 'verdent',
    shrineText: 'Vines coil around a cracked statue, alive with dew.',
    blessing: { type: 'MORNING_OVERGROWTH', value: -8, duration: 'CYCLE' },
  },
  {
    id: 'oryth',
    name: 'Oryth',
    domains: ['Paths', 'Wards'],
    generation: 'Other',
    rarity: 'uncommon',
    districtAffinity: 'any',
    shrineText: 'A worn road-marker stands amid prayer ribbons.',
    blessing: { type: 'ACTION_COST', value: -1, duration: 'NIGHT' },
  },
  {
    id: 'dack',
    name: 'Dack',
    domains: ['Courage', 'Endurance'],
    generation: 'Second',
    rarity: 'common',
    districtAffinity: 'heart',
    shrineText: 'A battered helm rests on a plinth, still warm.',
    blessing: { type: 'PACK_STAMINA', value: 1, duration: 'NIGHT' },
  },
  {
    id: 'freamalra',
    name: 'Freamalra',
    domains: ['Calm', 'Silence'],
    generation: 'Ascended',
    rarity: 'rare',
    districtAffinity: 'arcane',
    shrineText: 'A candlelit bowl hums with a steady, cooling tone.',
    blessing: { type: 'MORNING_TENSION', value: -8, duration: 'CYCLE' },
  },
  {
    id: 'chondath',
    name: 'Chondath',
    domains: ['Craft', 'Shelter'],
    generation: 'Other',
    rarity: 'uncommon',
    districtAffinity: 'any',
    shrineText: 'A bundle of chisels and nails crowns a new-cut stone.',
    blessing: { type: 'HOUSING_REWARD', value: 1, duration: 'NIGHT' },
  },
  {
    id: 'eroryol',
    name: 'Eroryol',
    domains: ['Watch', 'Diligence'],
    generation: 'Second',
    rarity: 'common',
    districtAffinity: 'heart',
    shrineText: 'A tall lantern glows with oil that never dims.',
    blessing: { type: 'ACTION_COST', value: -1, duration: 'NIGHT' },
  },
  {
    id: 'kal',
    name: 'Kal',
    domains: ['Oaths', 'Steel'],
    generation: 'Ascended',
    rarity: 'rare',
    districtAffinity: 'any',
    shrineText: 'A cracked blade is wedged into the stone as a vow.',
    blessing: { type: 'PACK_POWER', value: 1, duration: 'NIGHT' },
  },
  {
    id: 'layl',
    name: 'Layl',
    domains: ['Grace', 'Rest'],
    generation: 'Other',
    rarity: 'common',
    districtAffinity: 'verdent',
    shrineText: 'Soft cloth banners sway over a bed of smooth pebbles.',
    blessing: { type: 'MORNING_CAMP', value: -6, duration: 'CYCLE' },
  },
];

export const GOD_BY_ID = GODS.reduce((acc, god) => {
  acc[god.id] = god;
  return acc;
}, {});
